# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Schema.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0cSchema.proto\"\x84\x01\n\x0bLightUpGame\x12\x0c\n\x04name\x18\x01 \x01(\t\x12 \n\x05games\x18\x02 \x03(\x0b\x32\x11.LightUpGame.Game\x1a\x45\n\x04Game\x12\x14\n\x0cPuzzleAmount\x18\x01 \x01(\x05\x12\x12\n\nPuzzleSize\x18\x02 \x01(\t\x12\x13\n\x0bPuzzleState\x18\x03 \x03(\tb\x06proto3')



_LIGHTUPGAME = DESCRIPTOR.message_types_by_name['LightUpGame']
_LIGHTUPGAME_GAME = _LIGHTUPGAME.nested_types_by_name['Game']
LightUpGame = _reflection.GeneratedProtocolMessageType('LightUpGame', (_message.Message,), {

  'Game' : _reflection.GeneratedProtocolMessageType('Game', (_message.Message,), {
    'DESCRIPTOR' : _LIGHTUPGAME_GAME,
    '__module__' : 'Schema_pb2'
    # @@protoc_insertion_point(class_scope:LightUpGame.Game)
    })
  ,
  'DESCRIPTOR' : _LIGHTUPGAME,
  '__module__' : 'Schema_pb2'
  # @@protoc_insertion_point(class_scope:LightUpGame)
  })
_sym_db.RegisterMessage(LightUpGame)
_sym_db.RegisterMessage(LightUpGame.Game)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _LIGHTUPGAME._serialized_start=17
  _LIGHTUPGAME._serialized_end=149
  _LIGHTUPGAME_GAME._serialized_start=80
  _LIGHTUPGAME_GAME._serialized_end=149
# @@protoc_insertion_point(module_scope)


