# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Schema.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0cSchema.proto\";\n\x06Puzzle\x12\r\n\x05sizex\x18\x01 \x01(\x05\x12\r\n\x05sizey\x18\x02 \x01(\x05\x12\x13\n\x04Tile\x18\x03 \x03(\x0b\x32\x05.tile\"y\n\x04tile\x12\x0f\n\x07isWhite\x18\x01 \x01(\x08\x12\x0f\n\x07isBlack\x18\x02 \x01(\x08\x12\x0e\n\x06isLamp\x18\x03 \x01(\x08\x12\x0b\n\x03is0\x18\x04 \x01(\x08\x12\x0b\n\x03is1\x18\x05 \x01(\x08\x12\x0b\n\x03is2\x18\x06 \x01(\x08\x12\x0b\n\x03is3\x18\x07 \x01(\x08\x12\x0b\n\x03is4\x18\x08 \x01(\x08\"7\n\x07Puzzles\x12\x17\n\x06puzzle\x18\x01 \x03(\x0b\x32\x07.Puzzle\x12\x13\n\x0bpuzzlecount\x18\x02 \x01(\x05\x62\x06proto3')



_PUZZLE = DESCRIPTOR.message_types_by_name['Puzzle']
_TILE = DESCRIPTOR.message_types_by_name['tile']
_PUZZLES = DESCRIPTOR.message_types_by_name['Puzzles']
Puzzle = _reflection.GeneratedProtocolMessageType('Puzzle', (_message.Message,), {
  'DESCRIPTOR' : _PUZZLE,
  '__module__' : 'Schema_pb2'
  # @@protoc_insertion_point(class_scope:Puzzle)
  })
_sym_db.RegisterMessage(Puzzle)

tile = _reflection.GeneratedProtocolMessageType('tile', (_message.Message,), {
  'DESCRIPTOR' : _TILE,
  '__module__' : 'Schema_pb2'
  # @@protoc_insertion_point(class_scope:tile)
  })
_sym_db.RegisterMessage(tile)

Puzzles = _reflection.GeneratedProtocolMessageType('Puzzles', (_message.Message,), {
  'DESCRIPTOR' : _PUZZLES,
  '__module__' : 'Schema_pb2'
  # @@protoc_insertion_point(class_scope:Puzzles)
  })
_sym_db.RegisterMessage(Puzzles)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _PUZZLE._serialized_start=16
  _PUZZLE._serialized_end=75
  _TILE._serialized_start=77
  _TILE._serialized_end=198
  _PUZZLES._serialized_start=200
  _PUZZLES._serialized_end=255
# @@protoc_insertion_point(module_scope)
